### ISSUE TITLE
train and test?

### ISSUE THREAD

**Issue by chriszhenghaochen** [ywz978020607/HESIC#1]
Hi, thanks for amazing work,

Some questions regarding your work:

1. Would you mind provide an example script for train and test? 

2. I browse your "mywork" folder but only find test files and your command mentioned that there is a "newtrain.py" file, so I reckon that you mind missing uploading some files.

3. In the paper, it mentioned that you randomly select the samples from stereo2k and KITTI for training and testing, so would you mind providing your train and test list?

**Comment by ywz978020607** [comment]
Sorry, our code will be finished soon.
But the train code will not be published.

**Comment by ywz978020607** [comment]
Thanks for attention, our code will be finished soon, we will put the both dataset and test scripts description together.
However, the train code will not be published.

**Comment by ywz978020607** [comment]
Our code and models have been put on github~

**Comment by chriszhenghaochen** [comment]
thanks so much for the resource!

**Comment by amarzullo24** [comment]
Hi!
Do you plan to upload the scripts for generating plots too?
That would be nice!
