### ISSUE TITLE
alternative mirror

### ISSUE THREAD

**Issue by mwoedlinger** [ywz978020607/HESIC#2]
Hey, thanks a lot for the interesting work!

Is it possible to provide an alternative to pan baidu for datasets and pretrained_models?
Without a Chinese mobile phone number, it is impossible for me to create an account and download the data.

**Comment by ywz978020607** [comment]
Sorry about that, and I will provide the data through google drive in this week.

**Comment by mwoedlinger** [comment]
Awesome, thank you!
